name: test
on:
  workflow_dispatch:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_config: [ Debug, Release ]
        name: [ linux, macOS, windows ]
        include:
          - name: Linux
            os: ubuntu-latest
          - name: macOS
            os: macos-latest
          - name: Windows
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure
        shell: bash
        run: cmake -B build_dir -DCMAKE_BUILD_TYPE=${{ matrix.build_config }}

      - name: Build
        shell: bash
        run: cmake --build build_dir --config ${{ matrix.build_config }}

      - name: Run Tests
        working-directory: build_dir
        shell: bash
        run: ctest
