name: test
on:
  workflow_dispatch:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_config: [ Debug, Release ]
        # name: [ linux, macOS, windows ]
        name: [ linux, macOS ]
        include:
          - name: Linux
            os: ubuntu-latest
          - name: macOS
            os: macos-15
          # - name: Windows
          #   os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure & Build
        shell: bash
        run: |
          echo OSTYPE: "$OSTYPE"
          if [[ "$OSTYPE" == "linux-gnu" ]]; then
            export CC=/usr/bin/gcc-14
            export CXX=/usr/bin/g++-14
            gcc -v
            g++ -v
          fi

          cmake -B build_dir -DCMAKE_BUILD_TYPE=${{ matrix.build_config }}
          cmake --build build_dir --config ${{ matrix.build_config }}

      - name: Run Tests
        working-directory: build_dir
        shell: bash
        run: ctest
