name: test
on:
  workflow_dispatch:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_config: [ Debug, Release ]
        name: [ linux, macOS, windows ]
        include:
          - name: Linux
            os: ubuntu-latest
          - name: macOS
            os: macos-latest
          - name: Windows
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure
        shell: bash
        run: cmake -B . -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE}}

      - name: Build
        shell: bash
        run: cmake --build . --config ${{ env.BUILD_TYPE }}

      - name: Run Tests
        working-directory: ${{ env.APP_DIR }}
        shell: bash
        run: ctest
